// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using GD.Entity.Tables;
using Microsoft.EntityFrameworkCore;

namespace GD.Entity.Responsitories
{
    public partial class GDContext : DbContext
    {
      
    }
}